<a href="https://colab.research.google.com/github/AnnmariyaFrancis/ICT-Assignments/blob/main/Data_Preprocessing_AssignmentICT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import numpy as np
import pandas as pd

Importing the dataset

In [33]:
df=pd.read_csv('/content/titanic (1).csv')

In [34]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [35]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [36]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [37]:
data=df.values

In [38]:
df.nunique()

PassengerId    891
Survived         2
Pclass           3
Name           891
Sex              2
Age             88
SibSp            7
Parch            7
Ticket         681
Fare           248
Cabin          147
Embarked         3
dtype: int64

mention input and output columns

In [39]:
#df.Sex=df.Sex.map({'female':0,'male':1})#age must be scaled
#for ordinal variables onehotimporter can be used

In [55]:
X=df[['Pclass','Sex','Age','SibSp','Parch']]

In [56]:
X

Pclass     Sex   Age  SibSp  Parch
0         3    male  22.0      1      0
1         1  female  38.0      1      0
2         3  female  26.0      0      0
3         1  female  35.0      1      0
4         3    male  35.0      0      0
..      ...     ...   ...    ...    ...
886       2    male  27.0      0      0
887       1  female  19.0      0      0
888       3  female   NaN      1      2
889       1    male  26.0      0      0
890       3    male  32.0      0      0

[891 rows x 5 columns]

In [57]:
y=df['Survived']

In [58]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

Splitting into train and test

In [59]:
from sklearn.model_selection import train_test_split

In [60]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

In [61]:
X_train.shape

(712, 5)

In [71]:
X_test.shape

(179, 5)

In [62]:
y_train.shape

(712,)

Now we deal with the missing data

In [63]:
from sklearn .impute import SimpleImputer#simple imputer is a class we have to create a object 


In [64]:
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')#we can use strategy mean 

In [65]:
imputer.fit(X_train[['Pclass','Age','SibSp','Parch']])

SimpleImputer()

In [67]:
X_train[['Pclass','Age','SibSp','Parch']]=imputer.transform(X_train[['Pclass','Age','SibSp','Parch']])

In [68]:
X_train

Pclass     Sex        Age  SibSp  Parch
301     3.0    male  30.166232    2.0    0.0
309     1.0  female  30.000000    0.0    0.0
516     2.0  female  34.000000    0.0    0.0
120     2.0    male  21.000000    2.0    0.0
570     2.0    male  62.000000    0.0    0.0
..      ...     ...        ...    ...    ...
715     3.0    male  19.000000    0.0    0.0
767     3.0  female  30.500000    0.0    0.0
72      2.0    male  21.000000    0.0    0.0
235     3.0  female  30.166232    0.0    0.0
37      3.0    male  21.000000    0.0    0.0

[712 rows x 5 columns]

In [69]:
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')

In [72]:
imputer.fit(X_test[['Pclass','Age','SibSp','Parch']])

SimpleImputer()

In [73]:
X_test[['Pclass','Age','SibSp','Parch']]=imputer.transform(X_test[['Pclass','Age','SibSp','Parch']])

In [74]:
X_test

Pclass     Sex        Age  SibSp  Parch
862     1.0  female  48.000000    0.0    0.0
223     3.0    male  27.881849    0.0    0.0
84      2.0  female  17.000000    0.0    0.0
680     3.0  female  27.881849    0.0    0.0
535     2.0  female   7.000000    0.0    2.0
..      ...     ...        ...    ...    ...
796     1.0  female  49.000000    0.0    0.0
815     1.0    male  27.881849    0.0    0.0
629     3.0    male  27.881849    0.0    0.0
421     3.0    male  21.000000    0.0    0.0
448     3.0  female   5.000000    2.0    1.0

[179 rows x 5 columns]

Categorical Variable

In [75]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder #OneHotEncoder is used for categorical values


creates object of column transofromer and give parameters

In [95]:
ct=ColumnTransformer(transformers=[('encode',OneHotEncoder(),[0])],remainder='passthrough')

In [96]:
X_train=ct.fit_transform(X_train)

In [80]:
X_train

array([[1.0, 0.0, 0.0, ..., 30.166232394366194, 2.0, 0.0],
       [0.0, 1.0, 0.0, ..., 30.0, 0.0, 0.0],
       [1.0, 0.0, 1.0, ..., 34.0, 0.0, 0.0],
       ...,
       [1.0, 0.0, 1.0, ..., 21.0, 0.0, 0.0],
       [1.0, 0.0, 0.0, ..., 30.166232394366194, 0.0, 0.0],
       [1.0, 0.0, 0.0, ..., 21.0, 0.0, 0.0]], dtype=object)

In [97]:
X_test=ct.fit_transform(X_test)

In [98]:
X_test

array([[1.0, 0.0, 1.0, ..., 48.0, 0.0, 0.0],
       [0.0, 1.0, 0.0, ..., 27.881849315068493, 0.0, 0.0],
       [0.0, 1.0, 0.0, ..., 17.0, 0.0, 0.0],
       ...,
       [0.0, 1.0, 0.0, ..., 27.881849315068493, 0.0, 0.0],
       [0.0, 1.0, 0.0, ..., 21.0, 0.0, 0.0],
       [0.0, 1.0, 0.0, ..., 5.0, 2.0, 1.0]], dtype=object)

In [101]:
x1=oe.fit_transform(X)
x1

array([[ 2.,  1., 28.,  1.,  0.],
       [ 0.,  0., 51.,  1.,  0.],
       [ 2.,  0., 34.,  0.,  0.],
       ...,
       [ 2.,  0., nan,  1.,  2.],
       [ 0.,  1., 34.,  0.,  0.],
       [ 2.,  1., 42.,  0.,  0.]])

Handling target variables

In [86]:
from sklearn.preprocessing import LabelEncoder

In [87]:
le=LabelEncoder()

In [88]:
y=le.fit_transform(y)

In [89]:
y

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,

In [108]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train=df[['Pclass','Age','SibSp','Parch']] = sc.fit_transform(df[['Pclass','Age','SibSp','Parch']])
X_test=df[['Pclass','Age','SibSp','Parch']] = sc.transform(df[['Pclass','Age','SibSp','Parch']])

In [109]:
print(X_train)

[[ 0.82737724 -0.53037664  0.43279337 -0.47367361]
 [-1.56610693  0.57183099  0.43279337 -0.47367361]
 [ 0.82737724 -0.25482473 -0.4745452  -0.47367361]
 ...
 [ 0.82737724         nan  0.43279337  2.00893337]
 [-1.56610693 -0.25482473 -0.4745452  -0.47367361]
 [ 0.82737724  0.15850313 -0.4745452  -0.47367361]]
